# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.offerteCliente.web.OffertaClienteRigaPrmGridActionAdapter', 'it.caleido.thip.vendite.offerteCliente.web.YOffertaClienteRigaPrmGridActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.ordineVE.web.OrdineVenditaRigaPrmGridActionAdapter', 'it.caleido.thip.vendite.ordineVE.web.YOrdineVenditaRigaPrmGridActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/vendite/ordineVE/OrdineVenditaRigaSecRidefinizioni.js', 'it/caleido/thip/vendite/ordineVE/YOrdineVenditaRigaSecRidefinizioni.js', '2', 'N');
